;(function(global){
	global.Ta=global.Ta||{};
	Ta.hack=function(){
		return {params:'',
			conf:{sid:11253295,pf:2,hot:{}}		};
	};
})(this);
(function(f,j){function q(c){var c=c+"",a,b,d,e,h,g;d=c.length;b=0;for(a="";b<d;){e=c.charCodeAt(b++)&255;if(b==d){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4);a+="==";break}h=c.charCodeAt(b++);if(b==d){a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4|(h&240)>>
4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((h&15)<<2);a+="=";break}g=c.charCodeAt(b++);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>2);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((e&3)<<4|(h&240)>>4);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt((h&15)<<2|(g&192)>>6);a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g&63)}return a}function k(c){return(c=
document.cookie.match(RegExp("(?:^|;\\s)"+c+"=(.*?)(?:;\\s|$)")))?c[1]:""}function m(c,a,b){var c=c+"="+a+";path=/;domain=",a=window.location.host,d={"com.cn":1,"net.cn":1,"gov,cn":1,"com.hk":1},e=a.split(".");2<e.length&&(a=(d[e.slice(-2).join(".")]?e.slice(-3):e.slice(-2)).join("."));document.cookie=c+a+(b?";"+b:"")}function i(c){var a,b,d,e={};void 0===c?(d=window.location,c=d.host,a=d.pathname,b=d.search.substr(1),d=d.hash):(d=c.match(/\w+:\/\/((?:[\w-]+\.)+\w+)(?:\:\d+)?(\/[^\?\\\"\'\|\:<>]*)?(?:\?([^\'\"\\<>#]*))?(?:#(\w+))?/i)||
[],c=d[1],a=d[2],b=d[3],d=d[4]);if(b)for(var h=b.split("&"),g=0,f=h.length;g<f;g++){var l=h[g].split("=");e[l[0]]=l[1]}return{host:c,path:a,search:b,hash:d,param:e}}function n(c){return(c||"")+Math.round(2147483647*(Math.random()||0.5))*+new Date%1E10}function o(c,a){var b=document.createElement("script"),d=document.getElementsByTagName("script")[0];b.src=c;b.type="text/javascript";b.onload=b.onerror=b.onreadystatechange=function(){/loaded|complete|undefined/.test(b.readyState)&&(b.onload=b.onerror=
b.onreadystatechange=null,b.parentNode.removeChild(d),b=void 0,a())};d.parentNode.insertBefore(b,d)}function r(){var c=i(),a={dm:c.host,pvi:"",si:"",url:c.path,arg:encodeURIComponent(c.search||""),ty:1};a.pvi=function(){var b=k("pgv_pvi");b||(a.ty=0,b=n(),m("pgv_pvi",b,"expires=Sun, 18 Jan 2038 00:00:00 GMT;"));return b}();a.si=function(){var a=k("pgv_si");a||(a=n("s"),m("pgv_si",a));return a}();return a}function s(){var c=i(document.referrer),a=i();return{rdm:c.host,rurl:c.path,rarg:encodeURIComponent(c.search||
""),adt:a.param.ADTAG||a.param.adtag}}function t(){try{var c=navigator,a=screen||{width:"",height:"",colorDepth:""},b=document.body,d=a.width+"x"+a.height,e=a.colorDepth+"-bit",h=(c.language||c.userLanguage).toLowerCase(),g=c.javaEnabled()?1:0,f=(new Date).getTimezoneOffset()/60,a="";b.addBehavior&&(b.addBehavior("#default#clientCaps"),a=b.connectionType);var b={fl:"",scr:d,scl:e,lg:h,jv:g,tz:f,ct:a},l,i,j,k;if((l=c.plugins)&&(i=l.length))for(c=0;c<i;c++){if(j=l[c].description.match(/Shockwave Flash ([\d\.]+) \w*/))b.fl=
j[1]}else k=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"),b.fl=k.replace(/^.*\s+(\d+)\,(\d+).*$/,"$1.$2")}catch(m){return{}}return b}function u(){var c={};if("undefined"!=typeof _taadHolders&&0<_taadHolders.length)for(var a=0,b=_taadHolders,d=b.length;a<d;a++)c[b[a]]=c[b[a]]?c[b[a]]+1:1;var a=[],e;for(e in c)c.hasOwnProperty(e)&&a.push(e+"*"+c[e]);return{ext:"adid="+a.join(":")}}function v(){var c=k("pgv_info"),a=i().param.ssid,b="";a?(b="ty=0;ck=0;id="+a,m("pgv_info",
"ssid="+a+(c?"&"+c.replace(/ssid=[^&]*/,""):""))):(b=/(?:^|&)ssid=(\w+)/.exec(c))&&(b="ty=0;ck=1;id="+b[1]);return{pf:b}}function p(c){c=c||{};c.conf&&function(){var a=c.conf,b;for(b in a)a.hasOwnProperty(b)&&(f[b]=a[b])}();if(f.sid&&!Ta[f.sid]){for(var a=[],b=0,d=[r(),s(),{r2:f.sid,r3:"undefined"==typeof _speedMark?"-1":new Date-_speedMark,r4:f.pf||1},t(),u(),v(),{random:+new Date}],e=d.length;b<e;b++)for(var h in d[b])d[b].hasOwnProperty(h)&&a.push(h+"="+(d[b][h]||""));c.params&&a.push(c.params);
var a=Ta.src=("https:"==document.location.protocol?"https://pingtas":"http://pingtcss")+".qq.com/pingd?"+a.join("&"),g=new Image;Ta[f.sid]=g;g.onload=g.onerror=g.onabort=function(){g=g.onload=g.onerror=g.onabort=null;Ta[f.sid]=!0};g.src=a;(1*!f.pf||f.hot.isValid)&&w(a);f.logo&&255!=f.logo&&x(f.logo)}}function w(c){var a=window.location,b=a.host+a.pathname,d=a.pathname,e=function(){o("http://imgcache.qq.com/bossweb/ta/scripts/ping_hotclick_min.js",function(){(new hotclick(c)).watchClick()})};1*f.pf&&
RegExp(b).test(f.hot.url)?e():(a=f.sid,o("http://tcss.qq.com/heatmap/"+a%100+"/"+q(a)+".js?random="+ +new Date,function(){var a;if(window._Cnf&&(a=window._Cnf.url)){a=a.split("|");for(var b=0;b<a.length;b++)if(a[b]==d){e();break}}}))}function x(c){var a={9:"\u817e\u8baf\u5206\u6790",10:"\u7f51\u7ad9\u7edf\u8ba1",df:'<img src="http://tcss.qq.com/icon/toss_'+c+'.gif" border="0" />'};document.write(['<a href="http://ta.qq.com?ADTAG=FROUM.FOOTER.CLICK.ICON" title="\u817e\u8baf\u5206\u6790" target="_blank">',
a[c]||a.df,"<a>"].join(""))}j.pgvSendClick=function(c,a){var b=Ta.src.replace(/ext=[^&]*/,function(){return"ext="+("evtid"==a?"ty=0;evtid=":"adid=")+c}).replace(/r2=([^&]*)/,function(a,b){return"r2=a"+b});(new Image(1,1)).src=b};j.Ta=j.Ta||{};Ta.pgv=p;!Ta.async&&p(Ta.hack?Ta.hack():"")})({sid:"",pf:"",hot:{url:"",isValid:!1}},this);

